logging:
  level:
    org.springframework: ERROR
    org.hiberate: ERROR
    mc.shoppingcart: INFO
    
spring:
  application:
    name: ShoppingCartApplication
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: mc
    password: password
    initialization-mode: always
    schema: classpath*:db/${database}/schema/*.sql
    data: classpath*:db/${database}/data/*.sql
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  
database: h2