swagger: "2.0"
info:
  description: "Shopping Cart Client"
  version: "1.0.0"
  title: "Shopping Cart Client"
  license:
    name: "Eleanor Yu"
#host: "petstore.swagger.io"
basePath: "/api"
tags:
- name: "products"
  description: "Access to Products"
- name: "shoppingcart"
  description: "Access to Shopping Cart"
schemes:
#- "https"
- "http"
paths:
  "/products":
    get:
      tags:
        - products
      summary: Get All Products
      operationId: getAll
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  "/shoppingcart/{cart_name}":
    get:
      tags:
        - shoppingcart
      summary:  Get detail on certain shopping cart
      operationId: get
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: cart_name
          type:  string
          required: true
          description:  Cart Name
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Cart'
  "/shoppingcart":
    post:
      tags:
        - shoppingcart
      summary:  Create a shopping cart with an item
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: cartdetail
          schema:
            $ref: '#/definitions/Cart'
      responses:
        '200':
          description: OK
          schema:
            type: boolean
    put:
      tags:
        - shoppingcart
      summary:  Update Shopping Cart
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: cartdetail
          schema:
            $ref: '#/definitions/Cart'
      responses:
        '200':
          description: OK
          schema:
            type: boolean
definitions:
  Product:
    type: object
    properties:
      name:
        type: string
      price:
        type:  number
  Cart:
    type: object
    properties:
      name:
        type: string
      items:
        type: array
        items: 
          $ref: '#/definitions/CartItem'
  CartItem:
    type: object
    properties:
      itemName:
        type: string
      itemPrice:
        type: number
      numOfItem:
        type: number
        format: int64