CREATE SEQUENCE IF NOT EXISTS PRODUCT_SEQ START 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CART_SEQ START 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ITEM_SEQ START 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRODUCT (
	ID INT NOT NULL DEFAULT PRODUCT_SEQ.NEXTVAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE DOUBLE NOT NULL,
	UNIQUE KEY PRODUCT_NAME (NAME)
)
;

CREATE TABLE IF NOT EXISTS CART (
	ID INT NOT NULL DEFAULT CART_SEQ.NEXTVAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	UNIQUE KEY CART_NAME (NAME)
)
;

CREATE TABLE IF NOT EXISTS CART_ITEM (
	ID INT NOT NULL DEFAULT ITEM_SEQ.NEXTVAL PRIMARY KEY,
	CART_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	FOREIGN KEY (CART_ID) REFERENCES CART (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
